apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgeclusters.edge.knative.dev
  labels:
    app.kubernetes.io/name: knative-edge
    app.kubernetes.io/component: networking
    app.kubernetes.io/version: devel
    knative.dev/crd-install: "true"
spec:
  group: edge.knative.dev
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: TODO
          type: object
          x-kubernetes-validations:
            - rule: "size(self.spec.name) > 0"
            - rule: "!has(self.spec.zone) || size(self.spec.zone)> 0"
            - rule: "!has(self.spec.region) || size(self.spec.region)> 0"
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: 'Spec is the desired state of the EdgeCluster. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
              type: object
              required:
                - namespaces
              properties:
                zone:
                  description: The zone of the EdgeCluster
                  type: string
                region:
                  description: The region where the EdgeCluster is located
                  type: string
                namespaces:
                  description: The list of namespaces which are replicated to the EdgeCluster
                  type: array
                  items:
                    type: string
            status:
              description: 'Status is the current state of the EdgeCluster. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
              type: object
              properties:
                annotations:
                  description: Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.
                  type: object
                  additionalProperties:
                    type: string
                conditions:
                  description: Conditions the latest available observations of a resource's current state.
                  type: array
                  items:
                    description: 'Condition defines a readiness condition for a Knative resource. See: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties'
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant).
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      severity:
                        description: Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                connectionStatus:
                  description: An EdgeCluster can be either connected or disconnected.
                  type: string
                  enum:
                    - connected
                    - disconnected
                authenticationToken:
                  description: The authentication token of the EdgeCluster. This token is cannot be used in its raw form, as it doesn't include the signature or certificate authority hash.
                  type: string
      additionalPrinterColumns:
        - name: Zone
          type: string
          jsonPath: ".spec.zone"
        - name: Region
          type: string
          jsonPath: ".spec.region"
        - name: ConnectionStatus
          type: string
          jsonPath: ".state.connectionStatus"
  names:
    kind: EdgeCluster
    plural: edgeclusters
    singular: edgecluster
    categories:
      - knative-internal
      - networking
    shortNames:
      - ec
  scope: Cluster
