// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/jevvk/knative-edge/pkg/apis/edge.knative.dev/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EdgeClusterLister helps list EdgeClusters.
// All objects returned here must be treated as read-only.
type EdgeClusterLister interface {
	// List lists all EdgeClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EdgeCluster, err error)
	// Get retrieves the EdgeCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.EdgeCluster, error)
	EdgeClusterListerExpansion
}

// edgeClusterLister implements the EdgeClusterLister interface.
type edgeClusterLister struct {
	indexer cache.Indexer
}

// NewEdgeClusterLister returns a new EdgeClusterLister.
func NewEdgeClusterLister(indexer cache.Indexer) EdgeClusterLister {
	return &edgeClusterLister{indexer: indexer}
}

// List lists all EdgeClusters in the indexer.
func (s *edgeClusterLister) List(selector labels.Selector) (ret []*v1.EdgeCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EdgeCluster))
	})
	return ret, err
}

// Get retrieves the EdgeCluster from the index for a given name.
func (s *edgeClusterLister) Get(name string) (*v1.EdgeCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("edgecluster"), name)
	}
	return obj.(*v1.EdgeCluster), nil
}
