// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "knative.dev/edge/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// EdgeClusters returns a EdgeClusterInformer.
	EdgeClusters() EdgeClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// EdgeClusters returns a EdgeClusterInformer.
func (v *version) EdgeClusters() EdgeClusterInformer {
	return &edgeClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
