builds:
- id: controller
  dir: .
  main: ./cmd/controller
  ldflags:
  - -s
  - -w
- id: operator
  dir: .
  main: ./cmd/operator
  ldflags:
  - -s
  - -w
- id: proxy
  dir: .
  main: ./cmd/proxy
  ldflags:
  - -s
  - -w