apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-edge-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-edge-leader-election-role
subjects:
