apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: knative-edge-operator
  name: knative-edge-operator-metrics-service
  namespace: default
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    service: knative-edge
    control-plane: operator
