# permissions for end users to edit edgeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgecluster-editor-role
rules:
- apiGroups:
  - edge.jevv.dev
  resources:
  - edgeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.jevv.dev
  resources:
  - edgeclusters/status
  verbs:
  - get
