apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: knative-edge-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: knative-edge-metrics
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    service: knative-edge
  name: knative-edge-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: knative-edge
  namespace: knative-edge-metrics
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus-app: knative-edge
  podMonitorSelector:
    matchLabels:
      prometheus-app: knative-edge
  resources:
    requests:
      memory: 100Mi
  enableAdminAPI: false
  retention: 3h
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-knative-edge
  namespace: knative-edge-metrics
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: knative-edge
