// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "knative.dev/edge/pkg/client/clientset/versioned/typed/edge/v1"
)

type FakeEdgeV1 struct {
	*testing.Fake
}

func (c *FakeEdgeV1) EdgeClusters() v1.EdgeClusterInterface {
	return &FakeEdgeClusters{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEdgeV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
