kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-edge-manager
  labels:
    edge.knative.dev/controller: "true"
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-edge
rules:
  - apiGroups: ["edge.knative.dev"]
    resources: ["edgeclusters"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["edge.knative.dev"]
    resources: ["edgeclusters/status"]
    verbs: ["get", "list", "update", "patch", "watch"]
