# permissions for end users to edit edgeresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector-role
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      edge.jevv.dev/synchronize: true
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - get
  - list
  - create
  - update
  - delete
  - watch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - "serving.knative.dev"
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
