apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-edge-leader-election-rolebinding
  namespace: knative-edge-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-edge-leader-election-role
subjects:
- kind: ServiceAccount
  name: knative-edge-controller
